import os
from pathlib import Path
import sqlite3

import streamlit as st


DB_PATH = Path(__file__).resolve().parents[1] / "data" / "ttm.db"


def _database_url():
    value = os.getenv("DATABASE_URL", "")
    if value:
        return value
    try:
        return st.secrets.get("DATABASE_URL", "")
    except Exception:
        return ""


def _database_settings():
    names = ("DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD")
    values = {}
    for name in names:
        value = os.getenv(name, "")
        if not value:
            try:
                value = st.secrets.get(name, "")
            except Exception:
                value = ""
        values[name] = value
    return values


class Connection:
    def __init__(self, raw, postgres=False):
        self.raw = raw
        self.postgres = postgres

    def _sql(self, statement):
        return statement.replace("?", "%s") if self.postgres else statement

    def execute(self, statement, params=()):
        return self.raw.execute(self._sql(statement), params)

    def executemany(self, statement, params):
        if self.postgres:
            with self.raw.cursor() as cursor:
                cursor.executemany(self._sql(statement), params)
            return None
        return self.raw.executemany(self._sql(statement), params)

    def __enter__(self):
        self.raw.__enter__()
        return self

    def __exit__(self, exc_type, exc, tb):
        return self.raw.__exit__(exc_type, exc, tb)


def connect():
    url = _database_url()
    settings = _database_settings()
    if url or any(settings.values()):
        import psycopg
        from psycopg.rows import dict_row

        if url:
            raw = psycopg.connect(url, row_factory=dict_row)
        else:
            missing = [name for name, value in settings.items() if not value]
            if missing:
                raise RuntimeError(
                    "Faltan datos de conexión en Streamlit Secrets: "
                    + ", ".join(missing)
                )
            raw = psycopg.connect(
                host=settings["DB_HOST"],
                port=int(settings["DB_PORT"]),
                dbname=settings["DB_NAME"],
                user=settings["DB_USER"],
                password=settings["DB_PASSWORD"],
                sslmode="require",
                row_factory=dict_row,
            )
        return Connection(raw, postgres=True)

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(DB_PATH)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys=ON")
    return Connection(raw)


def is_integrity_error(exc):
    return exc.__class__.__name__ in {"IntegrityError", "UniqueViolation"}


def init_db():
    with connect() as con:
        if con.postgres:
            # Streamlit puede iniciar más de una sesión simultáneamente durante
            # un despliegue. Este bloqueo evita carreras al crear las tablas.
            con.execute("SELECT pg_advisory_xact_lock(hashtext(?))", ("ttm_init_db",))
            statements = [
                """CREATE TABLE IF NOT EXISTS users (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  username TEXT UNIQUE NOT NULL,
                  password_hash TEXT NOT NULL,
                  role TEXT NOT NULL CHECK(role IN ('admin','viewer')),
                  active INTEGER NOT NULL DEFAULT 1,
                  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                )""",
                """CREATE TABLE IF NOT EXISTS daily_sales (
                  sale_date DATE PRIMARY KEY, total_sales NUMERIC NOT NULL,
                  local_sales NUMERIC NOT NULL, delivery_sales NUMERIC NOT NULL,
                  tickets INTEGER NOT NULL, local_tickets INTEGER NOT NULL,
                  delivery_tickets INTEGER NOT NULL, cash NUMERIC DEFAULT 0,
                  card NUMERIC DEFAULT 0, transfer NUMERIC DEFAULT 0,
                  pedidos_ya NUMERIC DEFAULT 0, uber_eats NUMERIC DEFAULT 0,
                  rappi NUMERIC DEFAULT 0, other_delivery NUMERIC DEFAULT 0,
                  source_file TEXT, imported_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                )""",
                """CREATE TABLE IF NOT EXISTS product_sales (
                  sale_date DATE, product_raw TEXT, product_name TEXT, channel TEXT,
                  quantity NUMERIC, source_file TEXT,
                  PRIMARY KEY(sale_date, product_raw),
                  FOREIGN KEY(sale_date) REFERENCES daily_sales(sale_date) ON DELETE CASCADE
                )""",
                """CREATE TABLE IF NOT EXISTS expenses (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  expense_date DATE, category TEXT, description TEXT,
                  amount NUMERIC, source_file TEXT
                )""",
                """CREATE TABLE IF NOT EXISTS invoice_documents (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  document_hash TEXT UNIQUE NOT NULL,
                  source_bucket TEXT NOT NULL,
                  original_filename TEXT NOT NULL,
                  invoice_date DATE,
                  supplier_name TEXT,
                  supplier_tax_id TEXT,
                  invoice_number TEXT,
                  subtotal NUMERIC DEFAULT 0,
                  tax NUMERIC DEFAULT 0,
                  total NUMERIC DEFAULT 0,
                  expense_category TEXT NOT NULL DEFAULT 'Por clasificar',
                  description TEXT,
                  review_status TEXT NOT NULL DEFAULT 'Pendiente',
                  pdf_data BYTEA,
                  imported_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                )""",
            ]
        else:
            statements = [
                """CREATE TABLE IF NOT EXISTS users (
                  id INTEGER PRIMARY KEY, username TEXT UNIQUE COLLATE NOCASE,
                  password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','viewer')),
                  active INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP
                )""",
                """CREATE TABLE IF NOT EXISTS daily_sales (
                  sale_date TEXT PRIMARY KEY, total_sales REAL NOT NULL,
                  local_sales REAL NOT NULL, delivery_sales REAL NOT NULL,
                  tickets INTEGER NOT NULL, local_tickets INTEGER NOT NULL,
                  delivery_tickets INTEGER NOT NULL, cash REAL DEFAULT 0,
                  card REAL DEFAULT 0, transfer REAL DEFAULT 0,
                  pedidos_ya REAL DEFAULT 0, uber_eats REAL DEFAULT 0,
                  rappi REAL DEFAULT 0, other_delivery REAL DEFAULT 0,
                  source_file TEXT, imported_at TEXT DEFAULT CURRENT_TIMESTAMP
                )""",
                """CREATE TABLE IF NOT EXISTS product_sales (
                  sale_date TEXT, product_raw TEXT, product_name TEXT, channel TEXT,
                  quantity REAL, source_file TEXT,
                  PRIMARY KEY(sale_date, product_raw),
                  FOREIGN KEY(sale_date) REFERENCES daily_sales(sale_date) ON DELETE CASCADE
                )""",
                """CREATE TABLE IF NOT EXISTS expenses (
                  id INTEGER PRIMARY KEY, expense_date TEXT, category TEXT,
                  description TEXT, amount REAL, source_file TEXT
                )""",
                """CREATE TABLE IF NOT EXISTS invoice_documents (
                  id INTEGER PRIMARY KEY,
                  document_hash TEXT UNIQUE NOT NULL,
                  source_bucket TEXT NOT NULL,
                  original_filename TEXT NOT NULL,
                  invoice_date TEXT,
                  supplier_name TEXT,
                  supplier_tax_id TEXT,
                  invoice_number TEXT,
                  subtotal REAL DEFAULT 0,
                  tax REAL DEFAULT 0,
                  total REAL DEFAULT 0,
                  expense_category TEXT NOT NULL DEFAULT 'Por clasificar',
                  description TEXT,
                  review_status TEXT NOT NULL DEFAULT 'Pendiente',
                  pdf_data BLOB,
                  imported_at TEXT DEFAULT CURRENT_TIMESTAMP
                )""",
            ]
        for statement in statements:
            con.execute(statement)
